import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";

const MCP = import.meta.dirname;
const ROOT = join(MCP, "..");
const VALIDATOR = join(ROOT, "validator");
const TECHNIQUES = join(ROOT, "corpus", "techniques");
const OUT_DIR = join(MCP, "src", "generated");
const OUT_FILE = join(OUT_DIR, "corpus.ts");
const CHECK = process.argv.includes("--check");

// Pre-build gate: the corpus validator must pass before anything is compiled.
if (!existsSync(join(VALIDATOR, "node_modules"))) {
  const install = spawnSync("npm", ["ci"], { cwd: VALIDATOR, stdio: "inherit" });
  if (install.status !== 0) process.exit(install.status ?? 1);
}
const gate = spawnSync("npm", ["run", "validate"], { cwd: VALIDATOR, stdio: "inherit" });
if (gate.status !== 0) {
  console.error("mcp build aborted: corpus validation failed");
  process.exit(gate.status ?? 1);
}

const SECTION_MAP = {
  Mechanism: "mechanism",
  "How to apply — agent": "applyAgent",
  Narration: "narration",
  Verification: "verification",
  "Failure modes": "failureModes",
};

const files = [];
const entries = [];
for (const category of readdirSync(TECHNIQUES).sort()) {
  const dir = join(TECHNIQUES, category);
  for (const file of readdirSync(dir).sort().filter((f) => f.endsWith(".md"))) {
    const raw = readFileSync(join(dir, file), "utf8");
    files.push({ path: `${category}/${file}`, raw });
    entries.push(compileEntry(category, file, raw));
  }
}

const categories = [...new Set(entries.map((e) => e.category))].map((slug) => {
  const members = entries.filter((e) => e.category === slug);
  for (const e of members) {
    if (e.problem !== members[0].problem) {
      throw new Error(
        `${slug}: entries disagree on the category problem statement ('${e.id}' vs '${members[0].id}')`
      );
    }
  }
  return { slug, problem: members[0].problem, entryIds: members.map((e) => e.id) };
});

const hash = createHash("sha256");
for (const f of files) hash.update(f.path).update("\0").update(f.raw).update("\0");
const corpusHash = hash.digest("hex");

const bundle = { categories, entries };
const generated = `// Generated by mcp/build.mjs from corpus/ — do not edit by hand.
import type { CorpusBundle } from "../types.js";

export const CORPUS_HASH = ${JSON.stringify(corpusHash)};

export const CORPUS: CorpusBundle = ${JSON.stringify(bundle, null, 2)};
`;

if (CHECK) {
  const existing = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, "utf8") : null;
  if (existing !== generated) {
    console.error("stale corpus bundle: src/generated/corpus.ts does not match corpus/ — run `npm run build`");
    process.exit(1);
  }
  console.log("corpus bundle is current");
} else {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, generated);
  console.log(`compiled ${entries.length} entries, ${categories.length} categories (corpus ${corpusHash.slice(0, 12)})`);
}

function compileEntry(category, file, raw) {
  const match = raw.match(/^---\n([\s\S]+?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(`${category}/${file}: no frontmatter`);
  const fm = parseYaml(match[1]);
  const sections = splitSections(match[2]);

  const picked = {};
  for (const [heading, key] of Object.entries(SECTION_MAP)) {
    if (!(heading in sections)) throw new Error(`${category}/${file}: missing section '${heading}'`);
    picked[key] = sections[heading];
  }

  return {
    id: fm.id,
    name: fm.name,
    type: fm.type,
    category,
    problem: fm.problem,
    intentSignals: fm.intent_signals,
    related: fm.related ?? {},
    evidence: fm.evidence,
    sources: fm.sources ?? [],
    siteUrl: `https://contextoverflow.org/${category}/${fm.id}/`,
    sections: { ...picked, verification: splitVerification(picked.verification, `${category}/${file}`) },
  };
}

function splitSections(body) {
  const parts = body.split(/^## (.+)$/m);
  const sections = {};
  for (let i = 1; i < parts.length; i += 2) sections[parts[i].trim()] = parts[i + 1].trim();
  return sections;
}

/**
 * Every entry's Verification is exactly a '- **Human:**' / '- **Agent:**'
 * bullet pair — no preamble, no extra bullets. Anything else fails the build
 * rather than being silently mangled in the served output.
 */
function splitVerification(text, where) {
  const match = text.match(/^- \*\*Human:\*\*\s*([\s\S]*?)^- \*\*Agent:\*\*\s*([\s\S]*)$/m);
  if (!match || !text.trimStart().startsWith("- **Human:**")) {
    throw new Error(`${where}: Verification section is not a Human/Agent bullet pair`);
  }
  const [, human, agent] = match;
  if (/^- \*\*/m.test(agent)) {
    throw new Error(`${where}: Verification has content beyond the Human/Agent pair`);
  }
  return { human: human.trim(), agent: agent.trim() };
}
