/**
 * Curated recall vocabulary — part of the deterministic matcher, reviewed as
 * code, never corpus content. Round 1 curated from dev-split miss families;
 * round 2 from blind register-diversity imagination. The holdout split has
 * never been read by any curator.
 *
 * ENTRY_ALIASES: per-entry paraphrases of intent signals in real user
 * registers. Indexed like signals, for category routing and entry ranking.
 *
 * SYNONYMS: single user word -> single corpus word, applied at query time
 * with a discounted weight. Both sides are stemmed at index build.
 */
export const ENTRY_ALIASES: Record<string, string[]> = {
  "action-first-when-clear": [
    "narrates every move instead of doing it",
    "announces the plan then just waits",
    "all talk no execution",
    "explains what it will do never does",
    "heres my plan sound good",
    "just execute already stop asking",
    "wont pull the trigger itself",
    "waiting for my nod every step",
    "does nothing until i say go",
    "confirmation dressed up as a question",
    "describes the edit instead of making it",
    "gun shy needs prodding to act",
    "drafts everything executes nothing",
    "waiting for a green light",
    "outlines the steps never starts",
    "asks questions instead of writing code",
    "asked for the fix got questions",
    "too timid to take action",
    "run the command without asking",
  ],
  "attention-filtering": [
    "latched onto my side comment instead",
    "replies get worse the longer we chat",
    "quality nosedives in long threads",
    "earlier tangent still steering every reply",
    "old context bleeding into new replies",
    "pasted a whole doc got mush back",
    "big document in word soup out",
    "irrelevant details hijack the response",
    "distracted by every stray remark",
    "throwaway aside derailed the whole reply",
    "responds to the noise not the ask",
    "long conversation turns replies to sludge",
    "fixated on an offhand remark",
    "mentioned it once won't let go",
    "answers the footnote not the headline",
    "keyed on the wrong sentence entirely",
    "context rot in long chats",
    "stale details poisoning fresh answers",
    "grabbed my example ignored the ask",
    "ten pages in replies go incoherent",
  ],
  "caution-as-evasion-loop": [
    "keeps asking am i sure",
    "endless would you like to continue",
    "shall i proceed after every step",
    "approve edit or rewrite again",
    "offers three options after i decided",
    "mother may i every single step",
    "needs a permission slip for everything",
    "i just keep typing proceed",
    "double checks instructions i already gave",
    "reconfirms what i already approved",
    "invents a blocker instead of checking",
    "safety theater instead of progress",
    "asks before every tiny edit",
    "keeps asking after i said yes",
    "checks in like a nervous intern",
    "clarifying questions for obvious things",
    "halts midway waiting for approval",
    "makes me choose instead of deciding",
    "which approach do you prefer",
    "every reply ends with a question",
    "keeps confirming never actually delivers",
    "presents alternatives requests my approval",
  ],
  "checkpoint-and-resume": [
    "save point before trying something risky",
    "bookmark this spot in the chat",
    "want a game save state",
    "snapshot the conversation to rewind later",
    "roll back to before it derailed",
    "restore point for conversations",
    "branch the exploration without losing mainline",
    "pin this moment so we return",
    "long thread drifted, early decisions buried",
    "undo button for the whole session",
    "quicksave before we experiment",
    "mark a known good state",
    "fork the chat to explore",
    "revert to an earlier point",
    "ctrl z for the conversation",
    "safe point before risky change",
    "like a git commit for conversations",
    "get back to where things worked",
  ],
  "context-compression": [
    "chat too long but work unfinished",
    "hitting the context window limit",
    "conversation maxed out cant continue",
    "compress the thread to keep going",
    "early details pushed out by noise",
    "old messages falling off the window",
    "summarize progress before we overflow",
    "condense this monster thread",
    "running out of room mid project",
    "context full, important stuff evaporating",
    "lost track after auto compact",
    "forgot requirements from message one",
    "long chat ignoring my earlier instructions",
    "token limit killing our progress",
    "distill the thread before continuing",
    "forgot the filenames we were using",
    "getting the conversation too long warning",
    "boil this down and keep going",
  ],
  "declared-success-without-proof": [
    "says done code doesn't compile",
    "claims tests pass never ran suite",
    "victory lap before anything runs",
    "bug fixed but still reproduces",
    "all green claim collapses first check",
    "success story with zero receipts",
    "migration reported clean table missing",
    "marks its own homework complete",
    "fixed in past tense nothing executed",
    "can't trust its done anymore",
    "declares deploy success site still broken",
    "everything passing shows no test output",
    "said tests passed half actually failed",
    "said fixed code completely unchanged",
    "done but only an empty stub",
    "announced success build still failing",
    "false positive success report again",
    "no evidence it ran anything",
    "swears it shipped nothing changed",
    "wrote the summary skipped the work",
    "told me green ci says red",
  ],
  "dependency-analysis-first": [
    "cart before the horse ordering",
    "built the roof before the foundation",
    "bit off more than it can chew",
    "boiling the ocean instead of chunking",
    "tried the whole migration in one shot",
    "needs breaking into smaller chunks",
    "superficial shallow edits smeared across codebase",
    "picked the easy piece first, hit blockers",
    "blocked halfway on unmapped prerequisite",
    "finished pieces useless waiting on unbuilt parts",
    "where do we even start, huge project",
    "everything depends on everything else",
    "whole feature at once no milestones",
    "rewrote the entire codebase one message",
    "giant diff touching sixty files",
    "massive PR impossible to review",
    "wanted incremental change got total rewrite",
    "eat the elephant one bite",
    "split this into separate tickets",
    "too much to tackle in one sitting",
    "dumped the whole app one reply",
  ],
  "disaggregate-before-agreeing": [
    "endorses my whole claim flaws included",
    "swallowed my half baked idea whole",
    "rubber stamps everything wholesale",
    "tell me which parts actually hold",
    "agreed with the shaky parts too",
    "all or nothing yes no feedback",
    "blessed weak assumptions riding solid points",
    "want to know where reasoning goes soft",
    "wholesale agreement on mixed claims",
    "want partial pushback not total verdicts",
    "praised my code missed the bugs",
    "review came back all compliments",
    "point out the weak spots specifically",
    "complimented everything critiqued nothing",
    "praised my broken architecture design",
    "agreed without checking my math",
    "want line by line critique",
  ],
  "eloquence-as-evasion": [
    "bad news buried under caveats",
    "key admission hidden in paragraph six",
    "polished essay dodging a plain no",
    "asked for status got a framework",
    "eloquent smokescreen around the real verdict",
    "flowery prose hiding the failure",
    "wrapped the no in three disclaimers",
    "had to dig for the confession",
    "hedging dressed up as thoroughness",
    "comprehensive overview instead of a status",
    "smooth paragraphs burying the ugly truth",
    "sugarcoats the verdict in velvet paragraphs",
    "never gives a straight answer",
    "beats around the bush every time",
    "buries the lede in every reply",
    "two paragraphs of hedging before substance",
    "ninety percent preamble ten percent answer",
    "dances around the actual answer",
    "long walkup before admitting failure",
    "diplomatic mush instead of a verdict",
  ],
  "ground-or-label": [
    "made up a library version",
    "hallucinated an api dead certain",
    "invented config flag hours wasted",
    "cited docs page that 404s",
    "guesses sound exactly like facts",
    "can't tell real from fabricated",
    "wrong with a straight face",
    "doubles down on fake details",
    "flags pulled from thin air",
    "never admits unsure states gospel",
    "confident voice zero sources",
    "wish it labeled its guesses",
    "recommended a package that doesn't exist",
    "attributed a made up quote",
    "cited a paper nobody can find",
    "never just says i don't know",
    "source doesn't actually say that",
    "so authoritative yet completely wrong",
    "invented statistics with precise numbers",
    "called a function that isn't real",
    "gave a link that goes nowhere",
  ],
  "is-the-user-actually-right": [
    "stop flattering me evaluate the claim",
    "want pushback not empty validation",
    "its agreement means nothing anymore",
    "praise feels automatic not earned",
    "want it to hold its ground",
    "tell me when i'm actually wrong",
    "need a critic not a cheerleader",
    "can't trust its yes anymore",
    "glazing me instead of checking claims",
    "hollow compliments make agreement worthless",
    "want honest disagreement with reasons",
    "sucking up instead of evaluating",
    "give me brutal honesty not flattery",
    "stop agreeing give me real feedback",
    "be a devils advocate sometimes",
    "critique my work instead of praising",
    "asked for criticism got compliments",
    "too agreeable to be useful",
    "wish it would tell me no",
    "honest assessment not automatic agreement",
  ],
  "mode-separation": [
    "building the plane while flying it",
    "spaghetti of half-built pieces",
    "plan keeps changing mid-implementation",
    "research design coding all tangled together",
    "half-built pieces everywhere, nothing finished",
    "no phases, everything happening at once",
    "kept pivoting mid-build, constant rework",
    "separate the planning from the building",
    "explore plan implement mushed together",
    "loses the plot partway through massive refactor",
    "output turns to soup by file forty",
    "runs out of steam mid-refactor, degrades",
    "half the functions are empty stubs",
    "response cut off mid function",
    "ten files started none finished",
    "got overwhelmed left a mess",
    "hit response limit mid build",
    "twelve files pasted nothing fits together",
    "do it in stages not all at once",
    "plan first then build piece by piece",
    "one giant code dump won't compile",
  ],
  "outside-view-first": [
    "called it simple then it spiraled",
    "rosy estimate blew up again",
    "two hour fix took all week",
    "scoped it with zero caveats",
    "underestimates every migration",
    "optimistic timeline no risks listed",
    "famous last words this is easy",
    "plan assumed nothing goes wrong",
    "quick win turned into a rabbit hole",
    "happy path plan ignored reality",
    "sunny scoping burned me again",
    "no mention of the usual landmines",
    "no discovery phase straight to output",
    "started building without scoping first",
    "dove in headfirst without checking anything",
    "zero due diligence before diving in",
    "treats every task as trivial",
    "didn't size up the job first",
    "leaps before it looks",
    "ready fire aim every time",
  ],
  "persistent-context-files": [
    "re-explaining the project every single morning",
    "groundhog day with every new session",
    "goldfish memory between chats",
    "total amnesia about our project",
    "blank slate every time i return",
    "still suggests the stack we ditched",
    "keeps using the database we migrated off",
    "redoing work that was already finished",
    "relitigating decisions we settled weeks ago",
    "wish it remembered the repo permanently",
    "acts like we never decided that",
    "constantly reminding it what we chose",
    "onboarding a new hire every day",
    "reintroduced a bug we already fixed",
    "pasting the same context every day",
    "asks what the project is again",
    "starts from scratch every conversation",
    "keeps forgetting my style guide",
    "wish it had long term memory",
    "acts like we just met",
    "fifty first dates with my ai",
  ],
  "re-read-the-brief": [
    "skimmed my message missed half",
    "dropped one of my requirements",
    "ignored the constraint i stated",
    "only did the first half",
    "touched the file i said not to",
    "started coding before i finished typing",
    "wrote a fix before knowing the bug",
    "guessed the framework never checked",
    "barreled ahead without the details",
    "selective hearing on my spec",
    "redo because it misread the request",
    "picked a random target without clarifying which",
    "answered before hearing the whole problem",
    "never asks questions just assumes",
    "didn't ask what i actually wanted",
    "rewrote everything without asking my preferences",
    "jumps the gun every single time",
    "shoots first asks questions never",
    "never opened a single file first",
    "duplicated helpers it never looked for",
    "wrote tests for code it never read",
    "never bothered reading the readme",
  ],
  "recentering": [
    "lost the plot mid conversation",
    "drifting off topic halfway through",
    "mixing up two projects in one thread",
    "answers referencing the wrong feature",
    "replies getting loopy deep in",
    "went off the rails mid session",
    "quality nosediving as the chat grows",
    "conflating separate workstreams now",
    "wandered away from the actual topic",
    "confused about which branch we're on",
    "contradicts what we agreed earlier",
    "asking questions i already answered",
    "abandoned the plan halfway through",
    "suddenly unsure what we're building",
    "chasing tangents instead of the task",
    "responses unraveling as we go",
    "veered into something unrelated entirely",
  ],
  "reflexive-agreement": [
    "total yes man never disagrees",
    "folds instantly when i push back",
    "agreed with both opposite positions",
    "flip flops whenever i object",
    "you're absolutely right every reply",
    "backpedals the second i challenge it",
    "caved even though it was correct",
    "bobblehead nodding along with everything",
    "opens with great point before checking",
    "spineless switches sides on pure pushback",
    "apologized and adopted my view instantly",
    "echo chamber mirrors my opinions back",
    "every response starts with great question",
    "tells me what i want to hear",
    "praised my intentionally terrible test idea",
    "zero pushback ever on anything",
    "calls every idea a great idea",
    "excellent point even when im wrong",
    "validates whatever claim i make",
    "sides with whoever spoke last",
  ],
  "rephrase-and-respond": [
    "not what i meant at all",
    "solved the neighboring problem instead",
    "asked for refactor got a redesign",
    "misread my intent and sprinted off",
    "mismatch surfaced after the merge",
    "want it to restate before executing",
    "read back my request in its words",
    "technically followed my words missed the point",
    "literal genie interpretation of my prompt",
    "days of rework from one misreading",
    "delivered the cousin of what i wanted",
    "confirm what i meant before running",
    "answered the question i didnt ask",
    "right answer to the wrong question",
    "why does it always solve the wrong problem",
    "verify it understood the assignment first",
    "play back my request before starting",
    "letter of my words not the spirit",
    "built something adjacent to my request",
    "paraphrase my ask before touching code",
  ],
  "self-ask-first": [
    "paste first think never",
    "went blank at the whiteboard",
    "cant debug in my head anymore",
    "brain atrophy from constant delegation",
    "ai crutch cant walk without it",
    "spoon fed code i cant judge",
    "skills rusting since it thinks for me",
    "outsourced my judgment entirely",
    "cant tell good from merely fluent",
    "dumber every month i lean on it",
    "reflex is pasting the raw problem dump",
    "let it make every design call",
    "not learning anything it writes everything",
    "cant write a loop without autocomplete",
    "tab tab accept without reading",
    "works but i cant explain why",
    "tutor me dont do my homework",
    "guiding questions instead of finished answers",
    "sparring partner not an answer machine",
    "give hints not the full answer",
    "muscle memory gone autocomplete does everything",
    "my own voice disappearing from drafts",
  ],
  "session-handoff": [
    "continue this in a fresh chat",
    "hand off to the next session",
    "new chat needs everything from this one",
    "pass the baton between conversations",
    "package up context for tomorrow",
    "closed the tab and poof, gone",
    "fresh window remembers nothing from yesterday",
    "migrate this conversation to another one",
    "session dying mid task, need continuity",
    "wrapping up, brief the next chat",
    "carry context over to tomorrow",
    "persist decisions across sessions",
    "export the state of this chat",
    "resume tomorrow without losing anything",
    "write a handover note for itself",
    "new chat without losing progress",
    "shift change briefing between sessions",
  ],
  "smallest-working-answer": [
    "just the value nothing else",
    "one word needed five paragraphs delivered",
    "dissertation for a one liner request",
    "tutorial when one value would do",
    "five hundred words for a yes",
    "skimming past headers to find the point",
    "restates my prompt before getting anywhere",
    "generic advice padding every reply",
    "covers every case except mine",
    "get to the point already",
    "history lesson bundled with every flag",
    "bullet points and headings for nothing",
    "scrolling three screens for one command",
    "just the code skip the explanation",
    "life story before the recipe",
    "in summary paragraph every single time",
    "key takeaways section nobody asked for",
    "narrates every step before and after",
    "emoji headers and bold everywhere",
    "padding like a school essay",
    "answer first details only if asked",
    "token count triple the actual content",
  ],
  "tree-of-thought-branching": [
    "married to its first idea",
    "tunnel vision on the first approach",
    "commits to the first thing it generates",
    "big design decision, zero options shown",
    "no alternatives ever considered",
    "asked for options, got one path",
    "trade-offs never weighed before committing",
    "alternatives justified after the fact",
    "want approaches compared before building",
    "architecture chosen as fait accompli",
    "days deep into an uncompared design",
    "one path elaborated, design space unexplored",
    "never explored a plan b",
    "give me pros and cons first",
    "sketch two or three approaches first",
    "locked into one solution immediately",
    "first draft became the final architecture",
    "no bake off between candidate designs",
    "picked a direction without comparing",
  ],
};

export const SYNONYMS: Record<string, string> = {
  "acquiesces": "agreement",
  "adamant": "confident",
  "addicted": "outsourcing",
  "affirmation": "praise",
  "agreeable": "agreement",
  "allegedly": "claims",
  "alternative": "alternatives",
  "alzheimers": "forgets",
  "amnesia": "forgets",
  "appeases": "agreement",
  "asskissing": "flattering",
  "assumed": "guesses",
  "assumes": "guesses",
  "assuming": "guesses",
  "assumption": "guesses",
  "assumptions": "guesses",
  "atrophied": "dumber",
  "atrophy": "dumber",
  "atrophying": "dumber",
  "authoritative": "confident",
  "autopilot": "outsourcing",
  "avalanche": "wall",
  "babysitting": "confirmation",
  "backpedals": "flipping",
  "ballooned": "quagmire",
  "barrels": "producing",
  "baseless": "guesses",
  "baton": "handing",
  "bitesized": "pieces",
  "blanked": "unable",
  "blathering": "padded",
  "bloated": "padded",
  "blocked": "blocking",
  "blockers": "blocking",
  "bluffing": "guesses",
  "bobblehead": "agreement",
  "bogus": "false",
  "boilerplate": "generic",
  "bookmark": "save",
  "bootlicking": "flattering",
  "brainrot": "dumber",
  "brevity": "short",
  "brownnosing": "flattering",
  "bs": "guesses",
  "bullshit": "guesses",
  "bullshitting": "guesses",
  "bureaucratic": "gates",
  "butters": "flattering",
  "capitulates": "flipping",
  "carryover": "continue",
  "caution": "stalls",
  "cautious": "stalls",
  "caves": "flipping",
  "certainty": "confident",
  "chatty": "padded",
  "checkpoint": "save",
  "cheerleader": "praise",
  "chunks": "pieces",
  "clarified": "understands",
  "clearance": "authorized",
  "cocksure": "confident",
  "colossal": "big",
  "compact": "summarize",
  "compaction": "summarize",
  "compress": "summarize",
  "concise": "short",
  "concocted": "invented",
  "concurs": "agreement",
  "confabulation": "invented",
  "criticism": "pushback",
  "critique": "pushback",
  "crutch": "outsourcing",
  "dawdles": "stalls",
  "decompose": "pieces",
  "dejavu": "re-explaining",
  "dementia": "forgets",
  "dependence": "outsourcing",
  "dependencies": "prerequisites",
  "dependency": "outsourcing",
  "dependent": "outsourcing",
  "derailed": "drift",
  "deskilling": "dumber",
  "disclaimers": "caveats",
  "discovery": "scoping",
  "disregarded": "ignored",
  "dissertation": "wall",
  "dithers": "stalls",
  "dives": "producing",
  "doormat": "agreement",
  "dory": "forgets",
  "doublechecking": "confirmation",
  "doublechecks": "confirmation",
  "dove": "producing",
  "dragging": "stalls",
  "dumb": "dumber",
  "echo": "agreement",
  "elephant": "big",
  "encyclopedia": "wall",
  "enormous": "big",
  "epic": "big",
  "erased": "forgets",
  "essay": "wall",
  "evidence": "receipts",
  "eyeballed": "guesses",
  "fabricated": "invented",
  "fabrication": "invented",
  "falsehoods": "false",
  "fawning": "flattering",
  "fictional": "invented",
  "fictitious": "invented",
  "filler": "padded",
  "firehose": "wall",
  "flatters": "flattering",
  "flattery": "flattering",
  "flipflops": "flipping",
  "fluff": "padded",
  "folds": "flipping",
  "forgetful": "forgets",
  "forgot": "forgets",
  "gargantuan": "big",
  "gaslighting": "false",
  "gaslit": "false",
  "giant": "big",
  "gibberish": "mush",
  "glazing": "flattering",
  "glossed": "misread",
  "goldfish": "forgets",
  "gospel": "facts",
  "gps": "crutch",
  "greenlight": "approved",
  "groundhog": "re-explaining",
  "groundwork": "scoping",
  "groveling": "flattering",
  "guessed": "guesses",
  "guesstimate": "estimate",
  "gunshy": "stalls",
  "gushing": "praise",
  "halfcocked": "producing",
  "hallucinated": "invented",
  "hallucinating": "invented",
  "hallucination": "invented",
  "halts": "stalls",
  "handholding": "confirmation",
  "handoff": "handing",
  "handover": "handing",
  "headlong": "producing",
  "hedging": "caveats",
  "helpless": "unable",
  "hesitant": "stalls",
  "hesitates": "stalls",
  "hint": "hints",
  "huge": "big",
  "hypeman": "praise",
  "hypes": "praise",
  "idiot": "dumber",
  "imaginary": "invented",
  "inaccurate": "wrong",
  "incomplete": "dropped",
  "increments": "pieces",
  "indecisive": "decided",
  "infodump": "wall",
  "insists": "confident",
  "jumped": "producing",
  "kowtows": "agreement",
  "leaps": "producing",
  "leapt": "producing",
  "lecture": "wall",
  "liar": "false",
  "lied": "false",
  "lies": "false",
  "longwinded": "long",
  "lowballed": "optimistic",
  "lying": "false",
  "mammoth": "big",
  "manifesto": "wall",
  "markdown": "headings",
  "massive": "big",
  "memento": "forgets",
  "mentor": "tutor",
  "midway": "halfway",
  "milestones": "phases",
  "mirror": "agreement",
  "misheard": "misread",
  "misinformation": "false",
  "misinterpreted": "misalignment",
  "misleading": "false",
  "misled": "false",
  "mismatch": "misalignment",
  "misread": "misalignment",
  "mistaken": "wrong",
  "misunderstood": "misread",
  "monolithic": "big",
  "monologue": "wall",
  "nags": "confirmation",
  "nervous": "stalls",
  "nonexistent": "invented",
  "novel": "wall",
  "obsequious": "flattering",
  "obvious": "clear",
  "ocean": "big",
  "offload": "outsourcing",
  "offloading": "outsourcing",
  "okayed": "approved",
  "omitted": "dropped",
  "onboarding": "re-explaining",
  "oneshot": "shot",
  "oneshotted": "shot",
  "option": "options",
  "outline": "plan",
  "overcautious": "stalls",
  "overconfident": "confident",
  "overexplaining": "padded",
  "overexplains": "padded",
  "overlooked": "ignored",
  "overreliance": "outsourcing",
  "overwhelmed": "big",
  "overwhelming": "big",
  "pandering": "flattering",
  "paraphrase": "restate",
  "permission": "confirmation",
  "persist": "save",
  "phantom": "invented",
  "piecemeal": "pieces",
  "placates": "agreement",
  "poof": "lost",
  "preamble": "padded",
  "prefer": "options",
  "premature": "producing",
  "prematurely": "producing",
  "prereqs": "prerequisites",
  "presumed": "guesses",
  "pretends": "claims",
  "proceed": "acting",
  "procrastinates": "stalls",
  "pushover": "agreement",
  "qualifiers": "caveats",
  "quiz": "tutor",
  "rambling": "padded",
  "recall": "remember",
  "recap": "summarize",
  "recollection": "remember",
  "recon": "scoping",
  "reconfirms": "confirmation",
  "redo": "restarting",
  "reexplain": "re-explaining",
  "references": "cited",
  "regressing": "dumber",
  "rehash": "re-explaining",
  "reliant": "outsourcing",
  "relitigate": "decisions",
  "remind": "remember",
  "reminding": "remember",
  "reonboard": "re-explaining",
  "repaste": "re-explaining",
  "reset": "forgets",
  "restate": "verify",
  "resume": "continue",
  "retention": "remember",
  "retracts": "flipping",
  "reword": "restate",
  "roadmap": "plan",
  "rollback": "back",
  "rosy": "optimistic",
  "rubberstamp": "approved",
  "rushed": "producing",
  "rushes": "producing",
  "rusty": "dumber",
  "salad": "mush",
  "savepoint": "save",
  "screed": "wall",
  "scroll": "skim",
  "sermon": "wall",
  "sharp": "skills",
  "sidetracked": "drift",
  "signoff": "approved",
  "simping": "flattering",
  "skimmed": "misread",
  "skipped": "dropped",
  "socratic": "questions",
  "soup": "dissolving",
  "spec": "brief",
  "spiel": "wall",
  "spineless": "flipping",
  "spiraled": "quagmire",
  "split": "breaking",
  "splitting": "breaking",
  "spoonfed": "outsourcing",
  "spoonfeeding": "outsourcing",
  "sprawling": "big",
  "sprints": "phases",
  "stages": "phases",
  "stateless": "forgets",
  "stubs": "unfinished",
  "subdivide": "pieces",
  "subtasks": "pieces",
  "succinct": "short",
  "suckup": "flattering",
  "sugarcoated": "wrapped",
  "supposedly": "claims",
  "swears": "claims",
  "sweeping": "big",
  "sycophancy": "flattering",
  "sycophant": "flattering",
  "sycophantic": "flattering",
  "tangent": "irrelevant",
  "tangled": "interleaved",
  "textwall": "wall",
  "tickets": "pieces",
  "timid": "stalls",
  "tldr": "long",
  "tradeoffs": "alternatives",
  "transfer": "migrate",
  "trivial": "simple",
  "truncated": "lost",
  "tutorial": "wall",
  "unaided": "yourself",
  "unbuilt": "unfinished",
  "underestimated": "optimistic",
  "unfounded": "guesses",
  "unreviewable": "big",
  "untrue": "false",
  "unwieldy": "big",
  "validates": "praise",
  "validation": "praise",
  "vanished": "lost",
  "verbose": "padded",
  "verbosity": "padded",
  "vibecoding": "outsourcing",
  "waffle": "padded",
  "wean": "outsourcing",
  "winged": "guesses",
  "wiped": "forgets",
  "wordy": "padded",
  "yapping": "padded",
  "yesman": "agreement",
  "yolo": "producing",
};
